

*** Unable to execute: '"makeindex"  -s "00_thesis.ist" -t "00_thesis.alg" -o "00_thesis.acr" "00_thesis.acn"' ***

Failed with error code 127.

Status report:

sh: makeindex: command not found

makeindex didn't create a transcript.
Check that makeindex has been installed and
is on your system's PATH.
Your PATH environment variable is set to: 
/usr/bin:/bin:/usr/sbin:/sbin
Try manually running:
"makeindex"  -s "00_thesis.ist" -t "00_thesis.alg" -o "00_thesis.acr" "00_thesis.acn"

