This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file ./00_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file 00_thesis.acn....done (221 entries accepted, 0 rejected).
Sorting entries.....done (1827 comparisons).
Generating output file 00_thesis.acr....done (125 lines written, 0 warnings).
Output written in 00_thesis.acr.
Transcript written in 00_thesis.alg.
